export const ROUTES = {
  root: '/',
  public: {
    home: '/',
    pricing: '/pricing',
    contact: '/contact',
  },
  auth: {
    adminLogin: '/auth/admin/login',
    merchantLogin: '/auth/merchant/login',
    merchantRegister: '/auth/merchant/register',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
  admin: {
    root: '/admin',
    dashboard: '/admin/dashboard',
    users: '/admin/users',
    pois: '/admin/pois',
    poisDetail: '/admin/pois/:id',
    poisMap: '/admin/pois/map',
    tours: '/admin/tours',
    toursCreate: '/admin/tours/create',
    toursEdit: '/admin/tours/:id/edit',
    analytics: '/admin/analytics',
  },
  merchant: {
    root: '/merchant',
    dashboard: '/merchant/dashboard',
    profile: '/merchant/profile',
    pois: '/merchant/pois',
    poisDetail: '/merchant/pois/:id',
    poisCreate: '/merchant/pois/create',
    poisMap: '/merchant/pois/map',
    history: '/merchant/history',
    analytics: '/merchant/analytics',
  },
} as const;
